using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace IntroToAsyncProgramming
{
    public class ExtensionMethodsPrimer
    {
        private string blogA = @"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras faucibus iaculis mauris, nec vehicula risus feugiat a. Suspendisse elementum facilisis consectetur. Suspendisse semper arcu id sem dapibus, vel cursus turpis malesuada. Duis ac eleifend ante. In semper luctus dui, id eleifend ante sagittis ut. Donec maximus leo vitae massa efficitur aliquet. Proin luctus, leo in aliquam porttitor, libero risus pharetra orci, a mollis metus nisi at lorem.                                    Phasellus massa erat, volutpat quis porta at, iaculis at mauris. Donec lacinia nibh id enim ullamcorper, sed vehicula sapien semper. Cras vestibulum a sapien sit amet consequat. Nam sit amet lobortis elit. Nunc convallis venenatis erat sed faucibus. Donec arcu tortor, viverra id ornare nec, maximus in risus. Aliquam erat volutpat. Mauris erat nisl, vulputate vitae molestie nec, tempor at nisl. Cras commodo, nibh ac dignissim rutrum, elit enim gravida lorem, eget accumsan sapien turpis at velit.                                    Fusce quis libero sed neque faucibus pulvinar. Donec varius metus quis massa tristique, sed sodales erat iaculis. Phasellus urna erat, aliquet non nunc eget, ultricies venenatis libero. Ut molestie arcu quis quam congue, a gravida lacus ornare. Mauris eget varius lacus. Etiam in elementum enim. Etiam rhoncus at augue vel facilisis. Duis lacinia enim eu nisi dapibus, a mattis odio commodo. Nullam dictum fringilla orci ac cursus. Fusce nec tempus metus. Maecenas consectetur sapien tempor malesuada lobortis. Vivamus vel cursus metus, a semper enim. Donec varius arcu a ipsum lacinia mattis eget at risus. Sed a augue lectus. Mauris vitae ultricies sapien. Morbi fringilla nec dolor ac lobortis.";

        private string blogB = @"Vivamus convallis lorem ac metus hendrerit, et rutrum massa mollis. Integer sed mi quis massa dignissim hendrerit nec sed orci. Curabitur vitae imperdiet velit, vel commodo risus. Quisque elementum vel neque a tempor. Praesent sagittis tortor eget libero dignissim auctor. Maecenas lacinia mauris non venenatis rhoncus. Pellentesque nisl nulla, fermentum et leo in, eleifend pellentesque elit. Donec magna felis, molestie at neque vitae, dignissim suscipit lacus. Aliquam eu orci ac ligula blandit fermentum. Nullam quis lectus lorem. In mattis augue magna, bibendum ultrices leo maximus sed. Suspendisse porta, tortor vitae tempor dignissim, odio nunc vulputate sem, vitae malesuada felis enim a orci. Sed varius, libero vitae bibendum pharetra, lacus nulla ornare tellus, at pretium lacus ante vel odio. Ut molestie ex at aliquet pellentesque. Sed hendrerit odio at vestibulum pulvinar.                                    Duis fermentum metus arcu, gravida faucibus dolor aliquet vel. Suspendisse potenti. In hac habitasse platea dictumst. Vestibulum eu tortor iaculis, fermentum metus id, sodales mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque nec nibh quis eros tempus semper ut at nisl. Nunc sit amet orci pellentesque, sodales sem id, interdum dui. Praesent sed ullamcorper libero. Curabitur vel laoreet sem. Praesent imperdiet urna ut porttitor pretium. Donec eget bibendum dolor. Nulla consequat eros ac enim facilisis, eget maximus erat posuere.Proin bibendum urna est, at pellentesque metus varius interdum. Quisque dolor leo, eleifend quis orci vel, eleifend lobortis ex. Morbi posuere congue ex, nec varius est consequat vel. Morbi vitae purus a purus laoreet auctor ac ut sem. Mauris varius arcu quis leo tincidunt, bibendum faucibus arcu fringilla. Nulla gravida a orci non lobortis. Morbi vel malesuada metus. Nam vel ornare leo, ut dictum tellus. Nunc at felis ac dolor mattis commodo vitae et massa.";

        private string blogC = @"Vivamus aliquam varius nisl, nec facilisis erat tempus at. Cras imperdiet purus non risus malesuada, sed egestas diam ullamcorper. Pellentesque egestas quam eu nunc interdum maximus. Cras sit amet dui posuere, blandit ipsum tristique, eleifend lectus. Duis eget tortor malesuada, tristique augue a, gravida massa. Praesent et risus non magna consequat sodales. Sed nec facilisis mauris. Duis vehicula justo elit, non semper erat auctor eu. Vivamus vel purus eu ipsum viverra eleifend eleifend a erat. Suspendisse eget sem odio. Etiam auctor consequat dui eu ornare. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse lacinia lacinia lorem, vitae tempus tellus. In varius tempus congue. Nullam congue volutpat aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.                                In fringilla pellentesque risus non ornare. Nullam arcu magna, finibus sed pellentesque ut, mollis sed ipsum. Praesent eget lobortis neque. Nullam vulputate consectetur enim, ac tristique purus tempor nec. Nam porta justo velit, sit amet cursus augue molestie eu. Nullam aliquet sagittis felis vel ultricies. In tempor nisl quis consectetur semper.                                Phasellus tincidunt ex quis leo feugiat, ac imperdiet dui pellentesque. Phasellus suscipit lacus in sem iaculis placerat. Proin non lobortis nisi. Duis sed fringilla ante. Aenean convallis ex elit, eget euismod diam facilisis eget. Cras ut odio luctus nibh vulputate cursus non vel eros. Proin facilisis dapibus rutrum. Duis molestie diam id semper cursus. Sed sit amet purus pretium, venenatis eros vitae, tincidunt arcu. Aenean lobortis magna a tristique tempor. Suspendisse potenti. Sed quis pulvinar velit. Maecenas orci quam, lobortis a tortor eget, ornare luctus ipsum. Nunc vel enim nisl.";

        public string Shorten(string input, int wordsToTake = 5)
        {
            string[] words = input.Split(' ');
            string[] selectedWords = words.Take(wordsToTake).ToArray();

            string result = string.Join(" ", selectedWords);

            return $"{result}...";
        }
    }
}
